<?php

/**
 * @file
 * Primary module hooks for Метатэги наследников таксономии module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

use \Drupal\Core\Form\FormStateInterface;
use \Drupal\Core\Entity\ContentEntityInterface;

/**
 * Функция, добавляющая виджет в форм настроек таксономии
 *
 * @param array $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 */
function _metatag_taxchilds_settings_form(array &$form, FormStateInterface $form_state) {
	$entity = $form_state->getBuildInfo()['callback_object']->getEntity();
	$entity_type = $entity->getEntityType()->id();
	$config = Drupal::configFactory()->getEditable('metatag_taxchilds.' . $entity_type . '.' . $entity->id());

	$form['metatag_taxchilds'] = [
		'#type' => 'details',
		'#title' => t('Шаблон мета данных для наследников'),
		'#open' => false,
		'#weight' => 10
	];

	$form['metatag_taxchilds']['enable_override_meta'] = [
		'#type' => 'checkbox',
		'#title' => t('Переопределить мета данные наследников.'),
		'#default_value' => $config->get('enable_override')
	];

	$form['metatag_taxchilds']['meta_token_help'] = [
		'#theme' => 'token_tree_link',
		'#token_types' => ['node','commerce_product']
	];

	$form['metatag_taxchilds']['meta_title'] = [
		'#type'  => 'textfield',
		'#title' => 'Заголовок',
		'#size'  => 255,
		'#maxlength'  => 255,
		'#states' => [
			'visible' => [
				':input[name="enable_override_meta"]' => ['checked' => TRUE],
			]
		],
		'#default_value' => $config->get('title')
	];

	$form['metatag_taxchilds']['meta_description'] = [
		'#type'  => 'textarea',
		'#title' => 'Описание',
		'#states' => [
			'visible' => [
				':input[name="enable_override_meta"]' => ['checked' => TRUE],
			]
		],
		'#default_value' => $config->get('description')
	];

	$form['metatag_taxchilds']['meta_words'] = [
		'#type'  => 'textfield',
		'#title' => 'Ключевые слова',
		'#size'  => 255,
		'#maxlength'  => 255,
		'#states' => [
			'visible' => [
				':input[name="enable_override_meta"]' => ['checked' => TRUE],
			]
		],
		'#default_value' => $config->get('words')
	];

	$values_default = $config->get('alt_images');
	if (!is_array($values_default)) $values_default = [];
	$values = $form_state->get('num_images');
	if (empty($values)) {
		$values = count($values_default);
		if ($values < 1) $values = 1;
	}

	if ($form_state->getValue("alt_images_mode") !== null) {
		$values++;
		$form_state->set('num_images',$values);
	}

	$form['metatag_taxchilds']['alt_images'] = [
		"#type" => 'fieldset',
		"#title" => "ALT изображений",
		"#tree" => true,
		"#attributes" => [
			"id" => "taxonomy_meta_alt_images"
		],
		'#states' => [
			'visible' => [
				':input[name="enable_override_meta"]' => ['checked' => TRUE],
			]
		],
		"#tree" => true
	];
	for ($i = 0; $i < $values; $i++) {
		$form['metatag_taxchilds']['alt_images'][$i] = [ "#type" => "textfield" ];
		if (isset($values_default[$i]))
			$form['metatag_taxchilds']['alt_images'][$i]["#default_value"] = $values_default[$i];
	}

	$form['metatag_taxchilds']['alt_images_more'] = [
		"#type" => "button",
		"#value" => t("more"),
		"#name"  => "alt_images_mode",
		"#ajax" => [
			'callback' => "metatag_taxchilds_alt_images_more_callback",
			'wrapper' => "taxonomy_meta_alt_images"
		],
		'#states' => [
			'visible' => [
				':input[name="enable_override_meta"]' => ['checked' => TRUE],
			]
		]
	];

	$form['actions']['submit']['#submit'][] = 'metatag_taxchilds_submit_handler';
}
/**
 * Callback кнопки "Добавиь еще"
 */
function metatag_taxchilds_alt_images_more_callback(array &$form, FormStateInterface $form_state) {
	return $form['metatag_taxchilds']['alt_images'];
}

function metatag_taxchilds_preprocess_commerce_product(&$vars) {
	$metas = _metatag_taxchilds_get_meta($vars["product_entity"]);
	$alt_images = [];
	if (isset($metas["alt_images"]) && is_array($metas["alt_images"]))
		$alt_images = $metas["alt_images"];
	
	if (!empty($alt_images)) {
		
		// Подставляем значения
		$token_service = \Drupal::token();
		foreach ($alt_images as $key => $item) {
			$alt_images[$key] = $token_service->replace($item, [ $metas["#context"]["entity_type"] => $metas["#context"]["entity"] ], ['clear' => true]);
		}
		
		// Записываем alt
		foreach($vars["product"] as &$item) {
			if (isset($item["#theme"]) && $item["#theme"] === "field" && isset($item["#field_type"]) && $item["#field_type"] === "image") {
				foreach ($item as $key => &$image) {
					if (is_int($key) && empty($image["#item"]->alt) && isset($alt_images[$key]))
							$image["#item_attributes"]["alt"] = $alt_images[$key];
				}
			}
		}
	}
}
function metatag_taxchilds_preprocess_node(&$vars) {
	$metas = _metatag_taxchilds_get_meta($vars["node"]);
	$alt_images = [];
	if (isset($metas["alt_images"]) && is_array($metas["alt_images"]))
		$alt_images = $metas["alt_images"];
	
	if (!empty($alt_images)) {
		
		// Подставляем значения
		$token_service = \Drupal::token();
		foreach ($alt_images as $key => $item) {
			$alt_images[$key] = $token_service->replace($item, [ $metas["#context"]["entity_type"] => $metas["#context"]["entity"] ], ['clear' => true]);
		}
		
		// Записываем alt
		foreach($vars["content"] as &$item) {
			if (isset($item["#theme"]) && $item["#theme"] === "field" && isset($item["#field_type"]) && $item["#field_type"] === "image") {
				foreach ($item as $key => &$image) {
					if (is_int($key) && empty($image["#item"]->alt) && isset($alt_images[$key]))
							$image["#item_attributes"]["alt"] = $alt_images[$key];
				}
			}
		}
	}
}
function metatag_taxchilds_preprocess_responsive_image_formatter(&$vars) {
	if (isset($vars["item_attributes"]["alt"]))
		$vars["responsive_image"]["#attributes"]["alt"] = $vars["item_attributes"]["alt"];
}
/**
 * Implements hook_form_BASE_FORM_ID_alter().
 *
 * @param array $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 */
function metatag_taxchilds_form_taxonomy_term_form_alter(array &$form, FormStateInterface $form_state) {
	$entity = $form_state->getBuildInfo()['callback_object']->getEntity();
	if ($entity->id() !== NULL)
		_metatag_taxchilds_settings_form($form,$form_state);
}
/**
 * Implements hook_form_BASE_FORM_ID_alter().
 *
 * @param array $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 */
function metatag_taxchilds_form_taxonomy_vocabulary_form_alter(array &$form, FormStateInterface $form_state) {
	$entity = $form_state->getBuildInfo()['callback_object']->getEntity();
	if ($entity->id() !== NULL)
		_metatag_taxchilds_settings_form($form,$form_state);
}
/**
 * Submit handler attached to term and vocabulary forms.
 *
 * @param array $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 */
function metatag_taxchilds_submit_handler(array $form, FormStateInterface $form_state) {
	$entity = $form_state->getBuildInfo()['callback_object']->getEntity();
	$entity_type = $entity->getEntityType()->id();
	$form_values = $form_state->getValues();
	
	$alt_images = [];
	if (is_array($form_values['alt_images']))
	foreach ($form_values['alt_images'] as $item) {
		if (is_string($item) && strlen($item) > 0)
			$alt_images[] = $item;
	}

	if ($form_values["enable_override_meta"]) {
		\Drupal::configFactory()
			->getEditable('metatag_taxchilds.' . $entity_type . '.' . $entity->id())
			->set('enable_override', $form_values['enable_override_meta'])
			->set('title', $form_values['meta_title'])
			->set('description', $form_values['meta_description'])
			->set('words', $form_values['meta_words'])
			->set('alt_images', $alt_images)
			->save();
	} else {
		\Drupal::configFactory()
			->getEditable('metatag_taxchilds.' . $entity_type . '.' . $entity->id())
			->delete();
	}
}
/**
 * Implements hook_ENTITY_TYPE_delete().
 */
function metatag_taxchilds_taxonomy_vocabulary_delete(ContentEntityInterface $entity) {
	\Drupal::configFactory()->getEditable('metatag_taxchilds.'.$entity->getEntityType()->id().'.' . $entity->id())->delete();
}
/**
 * Implements hook_taxonomy_term_delete().
 */
function metatag_taxchilds_taxonomy_term_delete(ContentEntityInterface $entity) {
	\Drupal::configFactory()->getEditable('metatag_taxchilds.'.$entity->getEntityType()->id().'.' . $entity->id())->delete();
}
/**
 * Функция анализирует параметры страницы и выдает мета данные
 * @return array
 */
function _metatag_taxchilds_get_meta(?ContentEntityInterface $entity = null) {
	$title = null;
	$description = null;
	$keywords = null;
	$alt_images = null;

	if ($entity === null) {
		
		$route_match = \Drupal::routeMatch();
		$entity = $route_match->getParameter('node');
		
		if (!is_object($entity)) {
			$entity = $route_match->getParameter('commerce_product');
			if (!is_object($entity))
				return [];
		}
	}

	$arr = $entity->getFields();
	foreach ($arr as $key => $value) {
		if ($entity->get($key) instanceof \Drupal\Core\Field\EntityReferenceFieldItemList) {

			$entity_term = $entity->get($key)->entity;
			if ($entity_term === null || $entity_term->getEntityTypeId() !== "taxonomy_term") continue;

			$config = \Drupal::configFactory()->get("metatag_taxchilds.taxonomy_term.".$entity_term->id());

			$finded = false;

			// Смотрим описание и слова у настроек таксономии
			if ($config->get("enable_override")) {
				$finded = true;
				$title = $config->get("title");
				if (is_string($title) && strlen($title) < 1)
					$title = null;
				$description = $config->get("description");
				if (is_string($description) && strlen($description) < 1)
					$description = null;
				$keywords = $config->get("words");
				if (is_string($keywords) && strlen($keywords) < 1)
					$keywords = null;
				
				$alt_images = $config->get("alt_images");

			// Если не найдены, то смотрим у родителей
			} else {
				$parent = $entity_term;
				while ($parent->parent->count() > 0) {
					$parent = $parent->parent->entity;
					if ($parent === null) break;

					$config = \Drupal::configFactory()->get("metatag_taxchilds.taxonomy_term.".$parent->id());
					if ($config->get("enable_override")) {
						$finded = true;
						$title = $config->get("title");
						if (is_string($title) && strlen($title) < 1)
							$title = null;
						$description = $config->get("description");
						if (is_string($description) && strlen($description) < 1)
							$description = null;
						$keywords = $config->get("words");
						if (is_string($keywords) && strlen($keywords) < 1)
							$keywords = null;
							
						$alt_images = $config->get("alt_images");
						break;
					}

				}
			}

			// Если не найдено, то смотрим у настроек типа таксономии
			if (!$finded) {
				$config = \Drupal::configFactory()->get("metatag_taxchilds.taxonomy_vocabulary.".$entity_term->vid->target_id);

				if ($config->get("enable_override")) {
					$title = $config->get("title");
					if (is_string($title) && strlen($title) < 1)
						$title = null;
					$description = $config->get("description");
					if (is_string($description) && strlen($description) < 1)
						$description = null;
					$keywords = $config->get("words");
					if (is_string($keywords) && strlen($keywords) < 1)
						$keywords = null;
						
					$alt_images = $config->get("alt_images");
				}
			}
		}
	}
	return [
		"title"       => $title,
		"description" => $description,
		"keywords"    => $keywords,
		"alt_images"  => $alt_images,
		"#context"    => [
			"entity"      => $entity,
			"entity_type" => $entity->getEntityTypeId()
		]
	];
}
function metatag_taxchilds_metatags_alter(&$metatags,$context) {

	if (!isset($context["entity"]) || !is_object($context["entity"]) || !($context["entity"] instanceof ContentEntityInterface))
		return;

	$entityTypeId = $context["entity"]->getEntityType()->id();
	if ($entityTypeId !== "node" && $entityTypeId !== "commerce_product")
		return;

	$metas = _metatag_taxchilds_get_meta($context["entity"]);
	if (count($metas) < 1) return;
	if (!isset($metas["title"]) && !isset($metas["description"]) && !isset($metas["keywords"]))
		return;

	$entityTags = \Drupal::service('metatag.manager')->tagsFromEntity($context["entity"]);

	foreach ($metatags as $tagName=>$meta) {
		if (isset($metas[$tagName]) && $metas[$tagName] !== null && !isset($entityTags[$tagName])) {
			$metatags[$tagName] = $metas[$tagName];
		}
		unset($metas[$tagName]);
	}
	foreach ($metas as $tagName=>$meta) {
		if ($tagName !== '#context' && !isset($metatags[$tagName]) && $meta !== null)
			$metatags[$tagName] = $meta;
	}
}